services:
  alice:
    build: .
    container_name: chatp2p-alice
    hostname: alice
    command: ["--porta", "5000", "--apelido", "alice", "--pares", "bob:5000,carol:5000"] # Como to usando uma rede com hostname nao preicsa de localhost e portas diferentes (tipo DNS)
    stdin_open: true
    tty: true
    networks: [chatnet]

  bob:
    build: .
    container_name: chatp2p-bob
    hostname: bob
    command: ["--porta", "5000", "--apelido", "bob", "--pares", "alice:5000,carol:5000"]
    stdin_open: true
    tty: true
    networks: [chatnet]

  carol:
    build: .
    container_name: chatp2p-carol
    hostname: carol
    command: ["--porta", "5000", "--apelido", "carol", "--pares", "alice:5000,bob:5000"]
    stdin_open: true
    tty: true
    networks: [chatnet]

# A ideia aqui é criar uma rede para que os containers possam se comunicar entre si usando hostnames, sem precisar de portas diferentes ou localhost (IP).
networks:
  chatnet:
    driver: bridge