services:
  alice:
    build: .
    image: chatp2p:latest
    container_name: chatp2p-alice
    hostname: alice
    command: ["--porta", "5000", "--apelido", "alice", "--pares", "172.28.0.12:5000"] 
    stdin_open: true
    tty: true
    networks:
      chatnet:
        ipv4_address: 172.28.0.11

  bob:
    image: chatp2p:latest
    container_name: chatp2p-bob
    hostname: bob
    command: ["--porta", "5000", "--apelido", "bob", "--pares", "172.28.0.13:5000"]
    stdin_open: true
    tty: true
    networks:
      chatnet:
        ipv4_address: 172.28.0.12

  carol:
    image: chatp2p:latest
    container_name: chatp2p-carol
    hostname: carol
    command: ["--porta", "5000", "--apelido", "carol" ] 
    stdin_open: true
    tty: true
    networks:
      chatnet:
        ipv4_address: 172.28.0.13

  samuel:
    image: chatp2p:latest
    container_name: chatp2p-samuel
    hostname: samuel
    command: ["--porta", "5000", "--apelido", "samuel", "--pares", "172.28.0.13:5000"] 
    tty: true
    stdin_open: true
    networks:
      chatnet:
        ipv4_address: 172.28.0.14

  gabriel:
    image: chatp2p:latest
    container_name: chatp2p-gabriel
    hostname: gabriel
    command: ["--porta", "5000", "--apelido", "gabriel", "--pares", "172.28.0.14:5000"] 
    tty: true
    stdin_open: true
    networks:
      chatnet:
        ipv4_address: 172.28.0.15


networks:
  chatnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
